- name: "we should wait 30 seconds"
  wait_for_connection:
    timeout: 30
- name: backend compressed
  become: true
  copy:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu/backend/
- name: Extract compressed backend files
  become: true
  shell: |
    cd /home/ubuntu/backend
    tar -vxf artifact.tar.gz
    rm artifact.tar.gz
- name : Compile and start app 
  become : true 
  shell : | 
    cd /home/ubuntu/backend
    sudo npm install
    
    pm2 stop default
    pm2 start npm -- start